### ISSUE TITLE
Output not suitable for programmatic/scripted usage

### ISSUE THREAD

**Issue by zswanson** [chroju/parade#2]
Found this project while hunting for ParamStore CLIs and it was the best suited for daily use in our org. However the output from `parade get` isn't well suited for use in automation scripts. ie, I want to pass the value from parade to a docker container run as an env var in testing with `-e somevar=$(parade get /dev/mysecret -d)` but this breaks because the return is a complex string.
The output consists of:
`/dev/mysecret  secretvalue`
`<key><space><space><value>`

Not only does the key need to be stripped during scripted use, it has 2 spaces between the key and value so it caused a little confusing trying to use the `cut` tool in linux to retrieve the value field, as I expected the value to be field 2, and it turned out to be field 3 because of the extra space character.

I recommend that the output either:
1. Not contain the key at all
2. Have an option flag for only returning the value

**Comment by chroju** [comment]
@zswanson Sorry for the late reply. Thanks for using `parade` .

In [v0.3.0](https://github.com/chroju/parade/releases/tag/v0.3.0), `get` command now shows only the value. Indeed, this is simpler to handle. In the case of partial match search, it will continue to show both key and value.

By the way, I recommend `awk '{print $2}'` rather than `cut` to handle strings separated by space characters.
